import { useNavigate } from 'react-router-dom'

const FEATURES = [
  {
    icon: '📚',
    title: 'Every category covered',
    body: 'Books & notes, electronics, furniture, calculators, lab supplies — all in one place.',
  },
  {
    icon: '✨',
    title: 'AI-powered listings',
    body: 'Snap a photo. Our AI writes the title, description, category, and price range for you.',
  },
  {
    icon: '🎓',
    title: 'Built for students',
    body: 'Buy and sell within your campus community. No listing fees, no middlemen.',
  },
]

const HOW_IT_WORKS = [
  { step: '1', label: 'Sign up', desc: 'Create a free account with your email in seconds.' },
  { step: '2', label: 'List an item', desc: 'Upload a photo and let AI fill in the details for you.' },
  { step: '3', label: 'Sell & save', desc: 'Connect with buyers and pocket the difference.' },
]

export default function Landing() {
  const navigate = useNavigate()

  return (
    <div className="landing">
      {/* Nav */}
      <nav className="landing-nav">
        <span className="landing-brand">🎓 Student Marketplace</span>
        <div className="landing-nav-actions">
          <button className="btn ghost" onClick={() => navigate('/login')}>Log in</button>
          <button className="btn primary" onClick={() => navigate('/login?tab=signup')}>Sign up free</button>
        </div>
      </nav>

      {/* Hero */}
      <section className="hero">
        <div className="hero-inner">
          <span className="hero-badge">Free for students</span>
          <h1 className="hero-title">
            Buy and sell second-hand <span className="hero-accent">on campus</span>
          </h1>
          <p className="hero-sub">
            Textbooks, electronics, furniture, and more — listed in seconds with AI.
            Find great deals from students at your school.
          </p>
          <div className="hero-ctas">
            <button className="btn primary hero-cta" onClick={() => navigate('/login?tab=signup')}>
              Get started — it's free
            </button>
            <button className="btn ghost hero-cta" onClick={() => navigate('/login')}>
              Browse listings
            </button>
          </div>
        </div>
        <div className="hero-visual">
          <div className="mock-card">
            <div className="mock-thumb">📷</div>
            <div className="mock-body">
              <span className="chip">Electronics</span>
              <p className="mock-title">Texas Instruments TI-84 Plus</p>
              <p className="price">€60–€75</p>
              <p className="mock-ai-badge">✨ Generated by AI</p>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="features-section">
        <h2 className="section-title">Everything you need</h2>
        <div className="features-grid">
          {FEATURES.map((f) => (
            <div className="feature-card" key={f.title}>
              <span className="feature-icon">{f.icon}</span>
              <h3 className="feature-title">{f.title}</h3>
              <p className="feature-body">{f.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="how-section">
        <h2 className="section-title">How it works</h2>
        <div className="steps">
          {HOW_IT_WORKS.map((s, i) => (
            <div className="step" key={s.step}>
              <div className="step-number">{s.step}</div>
              <h3 className="step-label">{s.label}</h3>
              <p className="step-desc">{s.desc}</p>
              {i < HOW_IT_WORKS.length - 1 && <div className="step-arrow">→</div>}
            </div>
          ))}
        </div>
      </section>

      {/* CTA banner */}
      <section className="cta-banner">
        <h2 className="cta-title">Ready to declutter?</h2>
        <p className="cta-sub">Join your campus marketplace and start selling today.</p>
        <button className="btn primary hero-cta" onClick={() => navigate('/login?tab=signup')}>
          Create free account
        </button>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <span>🎓 Student Marketplace · Built for IE students</span>
      </footer>
    </div>
  )
}
